apiVersion: v1
kind: Service
metadata:
  name: inventory-backend-service
spec:
  type: NodePort
  selector:
    app: inventory
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080        
        
---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-backend
  spec:
  replicas: 2
strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    selector:
    matchLabels:
      app: inventory
      tier: backend
    template:
    metadata:
      labels:
        app: inventory
        tier: backend
    spec:
      containers:
      - name: java-app
        image: inventory-project-backend:latest

        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_NAME
        - name: DB_USER
          value: "user"
          name: DB_USER
           value: "password"

          readinessProbe:
            httpGet:    
             path: /actuator/health
             port: 8080 
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            
            configMapKeyRef:
              name: inventory-config
              key: DB_USER
        - name: DB_PASSWORD
          value: "password"

    
    
